<?php
require_once __DIR__ . '/../Core/Database.php';
require_once __DIR__ . '/../Core/App.php';
require_once __DIR__ . '/Mailer.php';
final class OrderNotifier
{
    public static function notifyOrderPlaced(int $orderId): bool
    {
        $order = self::findOrder($orderId); if (!$order) return false; $to = self::resolveRecipient($order); if ($to === '') return false;
        return Mailer::send(['to' => $to, 'subject' => 'Xác nhận đặt hàng thành công - Đơn #' . $orderId, 'body' => self::buildPlacedHtml($order), 'is_html' => true, 'meta' => ['event' => 'order_placed', 'order_id' => $orderId]]);
    }
    public static function notifyStatusChanged(int $orderId): bool
    {
        $order = self::findOrder($orderId); if (!$order) return false; $to = self::resolveRecipient($order); if ($to === '') return false;
        return Mailer::send(['to' => $to, 'subject' => 'Cập nhật trạng thái đơn hàng - Đơn #' . $orderId, 'body' => self::buildStatusHtml($order), 'is_html' => true, 'meta' => ['event' => 'order_status_changed', 'order_id' => $orderId, 'status' => $order['status'] ?? null, 'shipping_status' => $order['shipping_status'] ?? null, 'tracking_code' => $order['tracking_code'] ?? null]]);
    }
    private static function resolveRecipient(array $order): string { $to = trim((string) ($order['customer_email'] ?? '')); if ($to === '') $to = trim((string) ($order['user_email'] ?? '')); if ($to === '') $to = trim((string) App::config('mail.fallback_to', '')); return $to; }
    private static function findOrder(int $orderId): ?array
    {
        $db = Database::connection(); $st = $db->prepare('SELECT o.*, u.email AS user_email, u.name AS user_name FROM orders o LEFT JOIN users u ON u.id = o.user_id WHERE o.id = ? LIMIT 1'); $st->execute([$orderId]); $row = $st->fetch(PDO::FETCH_ASSOC); if (!$row) return null; $it = $db->prepare('SELECT oi.*, p.name AS product_name FROM order_items oi JOIN products p ON p.id = oi.product_id WHERE oi.order_id = ? ORDER BY oi.id ASC'); $it->execute([$orderId]); $row['items'] = $it->fetchAll(PDO::FETCH_ASSOC) ?: []; return $row;
    }
    private static function buildPlacedHtml(array $order): string
    {
        $shop = htmlspecialchars((string) App::config('site.name', 'ATINO STYLE'), ENT_QUOTES, 'UTF-8'); $name = htmlspecialchars((string) ($order['customer_name'] ?: ($order['user_name'] ?? 'Quý khách')), ENT_QUOTES, 'UTF-8'); $orderId = (int) ($order['id'] ?? 0); $money = number_format((int) ($order['total'] ?? 0), 0, ',', '.') . 'đ'; $paymentMethod = htmlspecialchars(self::paymentMethodLabel((string) ($order['payment_method'] ?? '')), ENT_QUOTES, 'UTF-8'); $status = htmlspecialchars(self::statusLabel((string) ($order['status'] ?? 'pending')), ENT_QUOTES, 'UTF-8'); $rows = self::itemRows($order['items'] ?? []);
        return "<!DOCTYPE html><html lang='vi'><head><meta charset='UTF-8'><title>Xác nhận đơn hàng</title></head><body style='margin:0;padding:0;background:#f4f6f8;font-family:Arial,Helvetica,sans-serif;color:#1f2937;'><div style='max-width:700px;margin:30px auto;padding:0 16px;'><div style='background:#111827;color:#fff;padding:24px 28px;border-radius:16px 16px 0 0;'><h1 style='margin:0;font-size:24px;'>{$shop}</h1><p style='margin:8px 0 0;color:#d1d5db;font-size:14px;'>Thông báo xác nhận đơn hàng</p></div><div style='background:#fff;padding:30px 28px;border:1px solid #e5e7eb;border-top:none;border-radius:0 0 16px 16px;'><p style='margin:0 0 16px;font-size:16px;'>Xin chào <strong>{$name}</strong>,</p><p style='margin:0 0 16px;line-height:1.7;'>Cảm ơn bạn đã đặt hàng tại <strong>{$shop}</strong>. Đơn hàng của bạn đã được ghi nhận thành công và đang chờ xử lý.</p><div style='margin:20px 0;padding:18px;background:#f9fafb;border:1px solid #e5e7eb;border-radius:12px;'><p style='margin:0 0 8px;'><strong>Mã đơn hàng:</strong> #{$orderId}</p><p style='margin:0 0 8px;'><strong>Trạng thái:</strong> {$status}</p><p style='margin:0 0 8px;'><strong>Phương thức thanh toán:</strong> {$paymentMethod}</p><p style='margin:0;'><strong>Tổng thanh toán:</strong> {$money}</p></div><h3 style='margin:24px 0 12px;'>Chi tiết sản phẩm</h3><table style='width:100%;border-collapse:collapse;font-size:14px;'><thead><tr><th style='text-align:left;border-bottom:1px solid #e5e7eb;padding:10px 8px;'>Sản phẩm</th><th style='text-align:center;border-bottom:1px solid #e5e7eb;padding:10px 8px;'>SL</th><th style='text-align:center;border-bottom:1px solid #e5e7eb;padding:10px 8px;'>Size</th><th style='text-align:center;border-bottom:1px solid #e5e7eb;padding:10px 8px;'>Màu</th><th style='text-align:right;border-bottom:1px solid #e5e7eb;padding:10px 8px;'>Giá</th></tr></thead><tbody>{$rows}</tbody></table><div style='margin-top:24px;padding:16px;background:#eff6ff;border-left:4px solid #2563eb;border-radius:10px;'><p style='margin:0;font-size:14px;line-height:1.7;color:#1e3a8a;'>Chúng tôi sẽ tiếp tục gửi email thông báo khi đơn hàng được xác nhận, chuyển sang đơn vị vận chuyển hoặc giao thành công.</p></div><div style='margin-top:28px;padding-top:18px;border-top:1px solid #e5e7eb;color:#6b7280;font-size:13px;line-height:1.7;'><p style='margin:0 0 6px;'><strong>{$shop}</strong></p><p style='margin:0 0 6px;'>Đây là email tự động từ hệ thống, vui lòng không trả lời email này.</p><p style='margin:0;'>Nếu cần hỗ trợ, vui lòng liên hệ bộ phận chăm sóc khách hàng của chúng tôi.</p></div></div></div></body></html>";
    }
    private static function buildStatusHtml(array $order): string
    {
        $shop = htmlspecialchars((string) App::config('site.name', 'ATINO STYLE'), ENT_QUOTES, 'UTF-8'); $name = htmlspecialchars((string) ($order['customer_name'] ?: ($order['user_name'] ?? 'Quý khách')), ENT_QUOTES, 'UTF-8'); $orderId = (int) ($order['id'] ?? 0); $status = htmlspecialchars(self::statusLabel((string) ($order['status'] ?? '')), ENT_QUOTES, 'UTF-8'); $shippingStatus = htmlspecialchars(self::shippingStatusLabel((string) ($order['shipping_status'] ?? '')), ENT_QUOTES, 'UTF-8'); $paymentStatus = htmlspecialchars(self::paymentStatusLabel((string) ($order['payment_status'] ?? '')), ENT_QUOTES, 'UTF-8'); $tracking = htmlspecialchars((string) (($order['tracking_code'] ?? '') !== '' ? $order['tracking_code'] : 'Chưa cập nhật'), ENT_QUOTES, 'UTF-8');
        return "<!DOCTYPE html><html lang='vi'><head><meta charset='UTF-8'><title>Cập nhật trạng thái đơn hàng</title></head><body style='margin:0;padding:0;background:#f4f6f8;font-family:Arial,Helvetica,sans-serif;color:#1f2937;'><div style='max-width:680px;margin:30px auto;padding:0 16px;'><div style='background:#111827;color:#fff;padding:24px 28px;border-radius:16px 16px 0 0;'><h1 style='margin:0;font-size:24px;'>{$shop}</h1><p style='margin:8px 0 0;color:#d1d5db;font-size:14px;'>Cập nhật trạng thái đơn hàng</p></div><div style='background:#fff;padding:30px 28px;border:1px solid #e5e7eb;border-top:none;border-radius:0 0 16px 16px;'><p style='margin:0 0 16px;font-size:16px;'>Xin chào <strong>{$name}</strong>,</p><p style='margin:0 0 16px;line-height:1.7;'>Đơn hàng <strong>#{$orderId}</strong> của bạn vừa được cập nhật trạng thái mới.</p><div style='margin:20px 0;padding:18px;background:#f9fafb;border:1px solid #e5e7eb;border-radius:12px;'><p style='margin:0 0 8px;'><strong>Trạng thái đơn hàng:</strong> {$status}</p><p style='margin:0 0 8px;'><strong>Trạng thái giao hàng:</strong> {$shippingStatus}</p><p style='margin:0 0 8px;'><strong>Trạng thái thanh toán:</strong> {$paymentStatus}</p><p style='margin:0;'><strong>Mã vận đơn:</strong> {$tracking}</p></div><div style='margin-top:18px;padding:16px;background:#ecfdf5;border-left:4px solid #10b981;border-radius:10px;'><p style='margin:0;font-size:14px;line-height:1.7;color:#065f46;'>Vui lòng theo dõi email và điện thoại để nhận thêm thông tin giao hàng từ cửa hàng hoặc đơn vị vận chuyển.</p></div><div style='margin-top:28px;padding-top:18px;border-top:1px solid #e5e7eb;color:#6b7280;font-size:13px;line-height:1.7;'><p style='margin:0 0 6px;'><strong>{$shop}</strong></p><p style='margin:0 0 6px;'>Đây là email tự động từ hệ thống, vui lòng không trả lời email này.</p><p style='margin:0;'>Nếu cần hỗ trợ, vui lòng liên hệ bộ phận chăm sóc khách hàng của chúng tôi.</p></div></div></div></body></html>";
    }
    private static function itemRows(array $items): string { if (!$items) return '<tr><td colspan="5" style="padding:12px 8px;">Không có dữ liệu sản phẩm.</td></tr>'; $html=''; foreach ($items as $item) { $name = htmlspecialchars((string) ($item['product_name'] ?? ''), ENT_QUOTES, 'UTF-8'); $qty=(int)($item['qty']??0); $size=htmlspecialchars((string)(($item['size']??'')!==''?$item['size']:'-'),ENT_QUOTES,'UTF-8'); $color=htmlspecialchars((string)(($item['color']??'')!==''?$item['color']:'-'),ENT_QUOTES,'UTF-8'); $price=number_format((int)($item['price']??0),0,',','.') . 'đ'; $html .= "<tr><td style='border-bottom:1px solid #f3f4f6;padding:10px 8px;'>{$name}</td><td style='border-bottom:1px solid #f3f4f6;padding:10px 8px;text-align:center;'>{$qty}</td><td style='border-bottom:1px solid #f3f4f6;padding:10px 8px;text-align:center;'>{$size}</td><td style='border-bottom:1px solid #f3f4f6;padding:10px 8px;text-align:center;'>{$color}</td><td style='border-bottom:1px solid #f3f4f6;padding:10px 8px;text-align:right;'>{$price}</td></tr>"; } return $html; }
    private static function statusLabel(string $status): string { return match ($status) { 'pending' => 'Chờ xác nhận', 'confirmed' => 'Đã xác nhận', 'shipping' => 'Đang giao hàng', 'completed' => 'Hoàn tất', 'cancelled' => 'Đã hủy', 'picking' => 'Đang chuẩn bị hàng', 'delivered' => 'Đã giao hàng', default => 'Chưa cập nhật', }; }
    private static function shippingStatusLabel(string $status): string { return match ($status) { 'picking' => 'Đang chuẩn bị hàng', 'shipping' => 'Đang vận chuyển', 'delivered' => 'Đã giao hàng', 'returned' => 'Hoàn trả', 'cancelled' => 'Đã hủy giao', default => 'Chưa cập nhật', }; }
    private static function paymentMethodLabel(string $value): string { return match ($value) { 'cod' => 'Thanh toán khi nhận hàng', 'bank_transfer', 'bank' => 'Chuyển khoản ngân hàng', 'qr' => 'Thanh toán QR Code', 'card' => 'Thẻ / VNPAY', default => 'Chưa cập nhật', }; }
    private static function paymentStatusLabel(string $value): string { return match ($value) { 'paid' => 'Đã thanh toán', 'unpaid' => 'Chưa thanh toán', 'failed' => 'Thanh toán thất bại', default => 'Chưa cập nhật', }; }
}
